/*Customer table*/
CREATE TABLE CUSTOMER
(DL_NUMBER CHAR(8) NOT NULL,
FNAME VARCHAR(25) NOT NULL,
MNAME VARCHAR(15),
LNAME VARCHAR(25) NOT NULL,
PHONE_NUMBER NUMBER(10) NOT NULL,
EMAIL_ID VARCHAR(30) NOT NULL,
STREET VARCHAR(30) NOT NULL,
CITY VARCHAR(30) NOT NULL,
STATE_NAME VARCHAR(20) NOT NULL,
ZIPCODE NUMBER(5) NOT NULL,
MEMBERSHIP_TYPE CHAR(1) DEFAULT 'N' NOT NULL,
MEMBERSHIP_ID CHAR(5),
CONSTRAINT CUSTOMERPK
PRIMARY KEY(DL_NUMBER));

/*Bike_category table*/
CREATE TABLE BIKE_CATEGORY
( CATEGORY_NAME VARCHAR(25) NOT NULL,
COST_PER_DAY NUMBER(5,2) NOT NULL,
LATE_FEE_PER_HOUR NUMBER(5,2) NOT NULL,
CONSTRAINT BIKECATEGORYPK
PRIMARY KEY(CATEGORY_NAME)
);


/*Location table*/
CREATE TABLE LOCATION
( LOCATION_ID CHAR(4) NOT NULL,
LOCATION_NAME VARCHAR(50) NOT NULL,
STREET VARCHAR(30) NOT NULL,
CITY VARCHAR(20) NOT NULL,
STATE_NAME VARCHAR(20) NOT NULL,
ZIPCODE NUMBER(5) NOT NULL,
CONSTRAINT LOCATIONPK
PRIMARY KEY (LOCATION_ID));

/*Bike table*/
CREATE TABLE BIKE
( REGISTRATION_NUMBER CHAR(7) NOT NULL,
MODEL_NAME VARCHAR(25) NOT NULL,
MAKE VARCHAR(25) NOT NULL,
MODEL_YEAR NUMBER(4) NOT NULL,
MILEAGE INTEGER NOT NULL,
BIKE_CATEGORY_NAME VARCHAR(25) NOT NULL,
LOC_ID CHAR(4) NOT NULL,
AVAILABILITY_FLAG CHAR(1) NOT NULL,
CONSTRAINT BIKEPK
PRIMARY KEY (REGISTRATION_NUMBER),
CONSTRAINT BIKEFK1
FOREIGN KEY (BIKE_CATEGORY_NAME) REFERENCES BIKE_CATEGORY(CATEGORY_NAME),
CONSTRAINT BIKEFK2
FOREIGN KEY (LOC_ID) REFERENCES LOCATION (LOCATION_ID)
);

/*Discount table*/
CREATE TABLE DISCOUNT
( DISCOUNT_CODE CHAR(4) NOT NULL,
DISCOUNT_NAME VARCHAR(25) NOT NULL,
EXPIRY_DATE DATE NOT NULL,
DISCOUNT_PERCENTAGE NUMBER(4,2) NOT NULL,
CONSTRAINT DISCOUNTPK
PRIMARY KEY (DISCOUNT_CODE),
CONSTRAINT DISCOUNTSK
UNIQUE (DISCOUNT_NAME)
);
	
/*Insurance table*/
CREATE TABLE INSURANCE
( INSURANCE_CODE CHAR(4) NOT NULL,
INSURANCE_NAME VARCHAR(50) NOT NULL,
COVERAGE_TYPE VARCHAR(200) NOT NULL,
COST_PER_DAY NUMBER(4,2) NOT NULL,
CONSTRAINT INSURANCEPK
PRIMARY KEY (INSURANCE_CODE),
CONSTRAINT INSURANCESK
UNIQUE (INSURANCE_NAME)
);




/*Booking table*/
CREATE TABLE BOOKING
(BOOKING_ID CHAR(5) NOT NULL,
FROM_DT_TIME TIMESTAMP NOT NULL,
RET_DT_TIME TIMESTAMP NOT NULL,
AMOUNT NUMBER(10,2) NOT NULL,
BOOKING_STATUS CHAR(1) NOT NULL,
PICKUP_LOC CHAR(4) NOT NULL,
DROP_LOC CHAR(4) NOT NULL,
REG_NUM CHAR(7) NOT NULL,
DL_NUM CHAR(8) NOT NULL,
INS_CODE CHAR(4),
ACT_RET_DT_TIME TIMESTAMP,
DISCOUNT_CODE CHAR(4),
CONSTRAINT BOOKINGPK
PRIMARY KEY (BOOKING_ID),
CONSTRAINT BOOKINGFK1
FOREIGN KEY (PICKUP_LOC) REFERENCES LOCATION (LOCATION_ID),
CONSTRAINT BOOKINGFK2
FOREIGN KEY (DROP_LOC) REFERENCES LOCATION (LOCATION_ID),
CONSTRAINT BOOKINGFK3
FOREIGN KEY (REG_NUM) REFERENCES BIKE(REGISTRATION_NUMBER),
CONSTRAINT BOOKINGFK4
FOREIGN KEY (DL_NUM) REFERENCES CUSTOMER (DL_NUMBER),
CONSTRAINT BOOKINGFK5
FOREIGN KEY (INS_CODE) REFERENCES INSURANCE(INSURANCE_CODE),
CONSTRAINT BOOKINGFK6
FOREIGN KEY (DISCOUNT_CODE) REFERENCES DISCOUNT (DISCOUNT_CODE));

/*Billing table*/
CREATE TABLE BILLING
( BILL_ID CHAR(6) NOT NULL,
BILL_DATE DATE NOT NULL,
BILL_STATUS CHAR(1) NOT NULL,
DISCOUNT_AMOUNT NUMBER(10,2) NOT NULL,
TOTAL_AMOUNT NUMBER(10,2) NOT NULL,
TAX_AMOUNT NUMBER(10,2) NOT NULL,
BOOKING_ID CHAR(5) NOT NULL,
TOTAL_LATE_FEE NUMBER(10,2) NOT NULL,
CONSTRAINT BILLINGPK
PRIMARY KEY (BILL_ID),
CONSTRAINT BILLINGFK1
FOREIGN KEY (BOOKING_ID) REFERENCES BOOKING(BOOKING_ID)
);

